spring:
  cloud:
    function:
      definition: sendText
    stream:
      kafka:
        binder:
          auto-create-topics: true
          brokers: IP_ADDRESS_WHERE_KAFKA_IS_HOSTED:9092
      bindings:
        sendText-in-0:
          destination: send-text-topic
          group: sms-group
server:
  port: 6061